### ISSUE TITLE
Problems parsing json response with "user_has_liked"

### ISSUE THREAD

**Issue by mariusw** [sachin-handiekar/jInstagram#1]
Hey Sachin!

Nice work on the jinstagram project!

I am trying out jinstagram and am experiencing a problem when using the getRecentMediaFeed() method.

The json response  includes "user_has_liked" info which for some reason has an ID that is a concatenation of the media id, and underscore and the user id:
<snip>..."user_has_liked": false, "id": "272980608_4245834", "user": {"username": "mariuswaldal"...</snip>

This id triggers an exception as it cannot be parsed to a number:
Caused by: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "272980608_4245834"

Have you experienced this yourself? It might be that the user_has_liked has been added after you last updated jinstagram.

Marius

**Comment by meleky** [comment]
Hey Sachin!

Thanks for your jInstagram support:)
Im trying to run your exam which includes 
" ...
                Verifier verifier = new Verifier(verifierCode);
		Token accessToken = service.getAccessToken(EMPTY_TOKEN, verifier);
		 
		Instagram instagram = new Instagram(accessToken);
		 
		UserInfo userInfo = instagram.getCurrentUserInfo();
		 
		System.out.println("***** User Info ******");
		System.out.println("Username : " + userInfo.getData().getUsername());
...."
I use 
               String callbackUrl = "http://reveal-it.appspot.com/oauthtest";
call back adress, and i registered instagram with my user & password and took my id and secret keys and put them in my source code like;

		String clientID = "yyy4357b25ba1b43330xxxx";
		String clientSecret="xxxxxxc0dd4abeb6421c38yyyyyy";

I am trying out jinstagram and am experiencing a problem when using the getRecentMediaFeed() method. After that, i verify my code but in ;
               Instagram instagram = new Instagram(accessToken);

part i took an exception which lines are below;

Exception in thread "main" java.lang.NoClassDefFoundError: com/google/gson/JsonSyntaxException
	at main.InstagramOku.main(InstagramOku.java:67)
Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonSyntaxException
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 1 more

Can you help me for this problem;

Thanks;
Melek

**Comment by sachin-handiekar** [comment]
Is the GSON library available in your classpath ?

**Comment by meleky** [comment]
Hi Sachin;

Thank you for your fast response. I realized that i added gson.lib.zip to my library when i correct it to gson.lib there were no problem. Thank you again for your amazing api for instagram.

Hava a nice day;
Melek

Android’de Yahoo Mail’den gönderildi

**Comment by zachfang** [comment]
Hi Sachin,

Thanks in advance for the fantastic API you provided. Is there any reason that I always get gson.JsonSyntaxException in either getRecentMediaFeed() or getPopularMedia()? I have included the Gson 2.4, 2.3.1 and 2.1 jar files, but still have the same issue. 

Thanks,
Zach
