### ISSUE TITLE
nested exception is org.jinstagram.auth.exceptions.OAuthException: Cannot extract an acces token

### ISSUE THREAD

**Issue by catinwarmhands** [sachin-handiekar/jInstagram#150]
Im getting this error after redirect from instagram login page
This error also occurs on http://jinstagram-sachinhandiekar.rhcloud.com/BasicWebDemo/

Screenshots:
(BasicWebDemo) http://pasteboard.co/1FCcrO2A.png
(My site) http://pasteboard.co/1FBWMdNW.png

**Comment by alexanderzafirov** [comment]
Same thing here. This is due to the fact that Instagram API returns a white space between the "access_token" key and value as such `"access_token": "1231231231231"`. The [regex](https://github.com/sachin-handiekar/jInstagram/blob/master/src/main/java/org/jinstagram/auth/model/Constants.java#L13) that is supposed to match that fails since it assumes there is no whitespace.

Should I make a quick fix PR? In the future should we not use regex but instead some JSON parsing?

**Comment by catinwarmhands** [comment]
Can you fix it?

**Comment by alexanderzafirov** [comment]
Like this #152

**Comment by catinwarmhands** [comment]
Thanks you a lot!

**Comment by sachin-handiekar** [comment]
Fixed in #151... Closing this issue.
